/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVoucherRouteImport } from './routes/admin.voucher'
import { Route as AdminTournamentRouteImport } from './routes/admin.tournament'
import { Route as AdminRewardRouteImport } from './routes/admin.reward'
import { Route as AdminReservasiRouteImport } from './routes/admin.reservasi'
import { Route as AdminProgramRouteImport } from './routes/admin.program'
import { Route as AdminPenggunaRouteImport } from './routes/admin.pengguna'
import { Route as AdminPengaturanRouteImport } from './routes/admin.pengaturan'
import { Route as AdminNotifikasiRouteImport } from './routes/admin.notifikasi'
import { Route as AdminMatchRouteImport } from './routes/admin.match'
import { Route as AdminKeuanganRouteImport } from './routes/admin.keuangan'
import { Route as AdminInstrukturRouteImport } from './routes/admin.instruktur'
import { Route as AdminFnbRouteImport } from './routes/admin.fnb'
import { Route as AdminCoachRouteImport } from './routes/admin.coach'
import { Route as AdminAiAssistantRouteImport } from './routes/admin.ai-assistant'
import { Route as AdminVoucherIndexRouteImport } from './routes/admin.voucher.index'
import { Route as AdminTournamentIndexRouteImport } from './routes/admin.tournament.index'
import { Route as AdminRewardIndexRouteImport } from './routes/admin.reward.index'
import { Route as AdminReservasiIndexRouteImport } from './routes/admin.reservasi.index'
import { Route as AdminKeuanganIndexRouteImport } from './routes/admin.keuangan.index'
import { Route as AdminFnbIndexRouteImport } from './routes/admin.fnb.index'
import { Route as AdminCoachIndexRouteImport } from './routes/admin.coach.index'
import { Route as AdminVoucherVoucherIdRouteImport } from './routes/admin.voucher.$voucherId'
import { Route as AdminTournamentNewRouteImport } from './routes/admin.tournament.new'
import { Route as AdminTournamentTournamentIdRouteImport } from './routes/admin.tournament.$tournamentId'
import { Route as AdminRewardRewardIdRouteImport } from './routes/admin.reward.$rewardId'
import { Route as AdminReservasiDetailRouteImport } from './routes/admin.reservasi.detail'
import { Route as AdminPenggunaUserIdRouteImport } from './routes/admin.pengguna.$userId'
import { Route as AdminKeuanganTransaksiRouteImport } from './routes/admin.keuangan.transaksi'
import { Route as AdminKeuanganReservasiRouteImport } from './routes/admin.keuangan.reservasi'
import { Route as AdminKeuanganPendapatanRouteImport } from './routes/admin.keuangan.pendapatan'
import { Route as AdminKeuanganOkupansiRouteImport } from './routes/admin.keuangan.okupansi'
import { Route as AdminFnbTransaksiRouteImport } from './routes/admin.fnb.transaksi'
import { Route as AdminTournamentTournamentIdIndexRouteImport } from './routes/admin.tournament.$tournamentId.index'
import { Route as AdminTournamentTournamentIdEditRouteImport } from './routes/admin.tournament.$tournamentId.edit'
import { Route as AdminCoachCoachIdJadwalRouteImport } from './routes/admin.coach.$coachId.jadwal'
import { Route as AdminCoachCoachIdHubRouteImport } from './routes/admin.coach.$coachId.hub'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVoucherRoute = AdminVoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTournamentRoute = AdminTournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardRoute = AdminRewardRouteImport.update({
  id: '/reward',
  path: '/reward',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservasiRoute = AdminReservasiRouteImport.update({
  id: '/reservasi',
  path: '/reservasi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramRoute = AdminProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPenggunaRoute = AdminPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotifikasiRoute = AdminNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchRoute = AdminMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKeuanganRoute = AdminKeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstrukturRoute = AdminInstrukturRouteImport.update({
  id: '/instruktur',
  path: '/instruktur',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFnbRoute = AdminFnbRouteImport.update({
  id: '/fnb',
  path: '/fnb',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoachRoute = AdminCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiAssistantRoute = AdminAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVoucherIndexRoute = AdminVoucherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminVoucherRoute,
} as any)
const AdminTournamentIndexRoute = AdminTournamentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTournamentRoute,
} as any)
const AdminRewardIndexRoute = AdminRewardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRewardRoute,
} as any)
const AdminReservasiIndexRoute = AdminReservasiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminReservasiRoute,
} as any)
const AdminKeuanganIndexRoute = AdminKeuanganIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminKeuanganRoute,
} as any)
const AdminFnbIndexRoute = AdminFnbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFnbRoute,
} as any)
const AdminCoachIndexRoute = AdminCoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCoachRoute,
} as any)
const AdminVoucherVoucherIdRoute = AdminVoucherVoucherIdRouteImport.update({
  id: '/$voucherId',
  path: '/$voucherId',
  getParentRoute: () => AdminVoucherRoute,
} as any)
const AdminTournamentNewRoute = AdminTournamentNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTournamentRoute,
} as any)
const AdminTournamentTournamentIdRoute =
  AdminTournamentTournamentIdRouteImport.update({
    id: '/$tournamentId',
    path: '/$tournamentId',
    getParentRoute: () => AdminTournamentRoute,
  } as any)
const AdminRewardRewardIdRoute = AdminRewardRewardIdRouteImport.update({
  id: '/$rewardId',
  path: '/$rewardId',
  getParentRoute: () => AdminRewardRoute,
} as any)
const AdminReservasiDetailRoute = AdminReservasiDetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => AdminReservasiRoute,
} as any)
const AdminPenggunaUserIdRoute = AdminPenggunaUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminPenggunaRoute,
} as any)
const AdminKeuanganTransaksiRoute = AdminKeuanganTransaksiRouteImport.update({
  id: '/transaksi',
  path: '/transaksi',
  getParentRoute: () => AdminKeuanganRoute,
} as any)
const AdminKeuanganReservasiRoute = AdminKeuanganReservasiRouteImport.update({
  id: '/reservasi',
  path: '/reservasi',
  getParentRoute: () => AdminKeuanganRoute,
} as any)
const AdminKeuanganPendapatanRoute = AdminKeuanganPendapatanRouteImport.update({
  id: '/pendapatan',
  path: '/pendapatan',
  getParentRoute: () => AdminKeuanganRoute,
} as any)
const AdminKeuanganOkupansiRoute = AdminKeuanganOkupansiRouteImport.update({
  id: '/okupansi',
  path: '/okupansi',
  getParentRoute: () => AdminKeuanganRoute,
} as any)
const AdminFnbTransaksiRoute = AdminFnbTransaksiRouteImport.update({
  id: '/transaksi',
  path: '/transaksi',
  getParentRoute: () => AdminFnbRoute,
} as any)
const AdminTournamentTournamentIdIndexRoute =
  AdminTournamentTournamentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminTournamentTournamentIdRoute,
  } as any)
const AdminTournamentTournamentIdEditRoute =
  AdminTournamentTournamentIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminTournamentTournamentIdRoute,
  } as any)
const AdminCoachCoachIdJadwalRoute = AdminCoachCoachIdJadwalRouteImport.update({
  id: '/$coachId/jadwal',
  path: '/$coachId/jadwal',
  getParentRoute: () => AdminCoachRoute,
} as any)
const AdminCoachCoachIdHubRoute = AdminCoachCoachIdHubRouteImport.update({
  id: '/$coachId/hub',
  path: '/$coachId/hub',
  getParentRoute: () => AdminCoachRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/ai-assistant': typeof AdminAiAssistantRoute
  '/admin/coach': typeof AdminCoachRouteWithChildren
  '/admin/fnb': typeof AdminFnbRouteWithChildren
  '/admin/instruktur': typeof AdminInstrukturRoute
  '/admin/keuangan': typeof AdminKeuanganRouteWithChildren
  '/admin/match': typeof AdminMatchRoute
  '/admin/notifikasi': typeof AdminNotifikasiRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pengguna': typeof AdminPenggunaRouteWithChildren
  '/admin/program': typeof AdminProgramRoute
  '/admin/reservasi': typeof AdminReservasiRouteWithChildren
  '/admin/reward': typeof AdminRewardRouteWithChildren
  '/admin/tournament': typeof AdminTournamentRouteWithChildren
  '/admin/voucher': typeof AdminVoucherRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/fnb/transaksi': typeof AdminFnbTransaksiRoute
  '/admin/keuangan/okupansi': typeof AdminKeuanganOkupansiRoute
  '/admin/keuangan/pendapatan': typeof AdminKeuanganPendapatanRoute
  '/admin/keuangan/reservasi': typeof AdminKeuanganReservasiRoute
  '/admin/keuangan/transaksi': typeof AdminKeuanganTransaksiRoute
  '/admin/pengguna/$userId': typeof AdminPenggunaUserIdRoute
  '/admin/reservasi/detail': typeof AdminReservasiDetailRoute
  '/admin/reward/$rewardId': typeof AdminRewardRewardIdRoute
  '/admin/tournament/$tournamentId': typeof AdminTournamentTournamentIdRouteWithChildren
  '/admin/tournament/new': typeof AdminTournamentNewRoute
  '/admin/voucher/$voucherId': typeof AdminVoucherVoucherIdRoute
  '/admin/coach/': typeof AdminCoachIndexRoute
  '/admin/fnb/': typeof AdminFnbIndexRoute
  '/admin/keuangan/': typeof AdminKeuanganIndexRoute
  '/admin/reservasi/': typeof AdminReservasiIndexRoute
  '/admin/reward/': typeof AdminRewardIndexRoute
  '/admin/tournament/': typeof AdminTournamentIndexRoute
  '/admin/voucher/': typeof AdminVoucherIndexRoute
  '/admin/coach/$coachId/hub': typeof AdminCoachCoachIdHubRoute
  '/admin/coach/$coachId/jadwal': typeof AdminCoachCoachIdJadwalRoute
  '/admin/tournament/$tournamentId/edit': typeof AdminTournamentTournamentIdEditRoute
  '/admin/tournament/$tournamentId/': typeof AdminTournamentTournamentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/ai-assistant': typeof AdminAiAssistantRoute
  '/admin/instruktur': typeof AdminInstrukturRoute
  '/admin/match': typeof AdminMatchRoute
  '/admin/notifikasi': typeof AdminNotifikasiRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pengguna': typeof AdminPenggunaRouteWithChildren
  '/admin/program': typeof AdminProgramRoute
  '/admin': typeof AdminIndexRoute
  '/admin/fnb/transaksi': typeof AdminFnbTransaksiRoute
  '/admin/keuangan/okupansi': typeof AdminKeuanganOkupansiRoute
  '/admin/keuangan/pendapatan': typeof AdminKeuanganPendapatanRoute
  '/admin/keuangan/reservasi': typeof AdminKeuanganReservasiRoute
  '/admin/keuangan/transaksi': typeof AdminKeuanganTransaksiRoute
  '/admin/pengguna/$userId': typeof AdminPenggunaUserIdRoute
  '/admin/reservasi/detail': typeof AdminReservasiDetailRoute
  '/admin/reward/$rewardId': typeof AdminRewardRewardIdRoute
  '/admin/tournament/new': typeof AdminTournamentNewRoute
  '/admin/voucher/$voucherId': typeof AdminVoucherVoucherIdRoute
  '/admin/coach': typeof AdminCoachIndexRoute
  '/admin/fnb': typeof AdminFnbIndexRoute
  '/admin/keuangan': typeof AdminKeuanganIndexRoute
  '/admin/reservasi': typeof AdminReservasiIndexRoute
  '/admin/reward': typeof AdminRewardIndexRoute
  '/admin/tournament': typeof AdminTournamentIndexRoute
  '/admin/voucher': typeof AdminVoucherIndexRoute
  '/admin/coach/$coachId/hub': typeof AdminCoachCoachIdHubRoute
  '/admin/coach/$coachId/jadwal': typeof AdminCoachCoachIdJadwalRoute
  '/admin/tournament/$tournamentId/edit': typeof AdminTournamentTournamentIdEditRoute
  '/admin/tournament/$tournamentId': typeof AdminTournamentTournamentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/ai-assistant': typeof AdminAiAssistantRoute
  '/admin/coach': typeof AdminCoachRouteWithChildren
  '/admin/fnb': typeof AdminFnbRouteWithChildren
  '/admin/instruktur': typeof AdminInstrukturRoute
  '/admin/keuangan': typeof AdminKeuanganRouteWithChildren
  '/admin/match': typeof AdminMatchRoute
  '/admin/notifikasi': typeof AdminNotifikasiRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pengguna': typeof AdminPenggunaRouteWithChildren
  '/admin/program': typeof AdminProgramRoute
  '/admin/reservasi': typeof AdminReservasiRouteWithChildren
  '/admin/reward': typeof AdminRewardRouteWithChildren
  '/admin/tournament': typeof AdminTournamentRouteWithChildren
  '/admin/voucher': typeof AdminVoucherRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/fnb/transaksi': typeof AdminFnbTransaksiRoute
  '/admin/keuangan/okupansi': typeof AdminKeuanganOkupansiRoute
  '/admin/keuangan/pendapatan': typeof AdminKeuanganPendapatanRoute
  '/admin/keuangan/reservasi': typeof AdminKeuanganReservasiRoute
  '/admin/keuangan/transaksi': typeof AdminKeuanganTransaksiRoute
  '/admin/pengguna/$userId': typeof AdminPenggunaUserIdRoute
  '/admin/reservasi/detail': typeof AdminReservasiDetailRoute
  '/admin/reward/$rewardId': typeof AdminRewardRewardIdRoute
  '/admin/tournament/$tournamentId': typeof AdminTournamentTournamentIdRouteWithChildren
  '/admin/tournament/new': typeof AdminTournamentNewRoute
  '/admin/voucher/$voucherId': typeof AdminVoucherVoucherIdRoute
  '/admin/coach/': typeof AdminCoachIndexRoute
  '/admin/fnb/': typeof AdminFnbIndexRoute
  '/admin/keuangan/': typeof AdminKeuanganIndexRoute
  '/admin/reservasi/': typeof AdminReservasiIndexRoute
  '/admin/reward/': typeof AdminRewardIndexRoute
  '/admin/tournament/': typeof AdminTournamentIndexRoute
  '/admin/voucher/': typeof AdminVoucherIndexRoute
  '/admin/coach/$coachId/hub': typeof AdminCoachCoachIdHubRoute
  '/admin/coach/$coachId/jadwal': typeof AdminCoachCoachIdJadwalRoute
  '/admin/tournament/$tournamentId/edit': typeof AdminTournamentTournamentIdEditRoute
  '/admin/tournament/$tournamentId/': typeof AdminTournamentTournamentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/ai-assistant'
    | '/admin/coach'
    | '/admin/fnb'
    | '/admin/instruktur'
    | '/admin/keuangan'
    | '/admin/match'
    | '/admin/notifikasi'
    | '/admin/pengaturan'
    | '/admin/pengguna'
    | '/admin/program'
    | '/admin/reservasi'
    | '/admin/reward'
    | '/admin/tournament'
    | '/admin/voucher'
    | '/admin/'
    | '/admin/fnb/transaksi'
    | '/admin/keuangan/okupansi'
    | '/admin/keuangan/pendapatan'
    | '/admin/keuangan/reservasi'
    | '/admin/keuangan/transaksi'
    | '/admin/pengguna/$userId'
    | '/admin/reservasi/detail'
    | '/admin/reward/$rewardId'
    | '/admin/tournament/$tournamentId'
    | '/admin/tournament/new'
    | '/admin/voucher/$voucherId'
    | '/admin/coach/'
    | '/admin/fnb/'
    | '/admin/keuangan/'
    | '/admin/reservasi/'
    | '/admin/reward/'
    | '/admin/tournament/'
    | '/admin/voucher/'
    | '/admin/coach/$coachId/hub'
    | '/admin/coach/$coachId/jadwal'
    | '/admin/tournament/$tournamentId/edit'
    | '/admin/tournament/$tournamentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/ai-assistant'
    | '/admin/instruktur'
    | '/admin/match'
    | '/admin/notifikasi'
    | '/admin/pengaturan'
    | '/admin/pengguna'
    | '/admin/program'
    | '/admin'
    | '/admin/fnb/transaksi'
    | '/admin/keuangan/okupansi'
    | '/admin/keuangan/pendapatan'
    | '/admin/keuangan/reservasi'
    | '/admin/keuangan/transaksi'
    | '/admin/pengguna/$userId'
    | '/admin/reservasi/detail'
    | '/admin/reward/$rewardId'
    | '/admin/tournament/new'
    | '/admin/voucher/$voucherId'
    | '/admin/coach'
    | '/admin/fnb'
    | '/admin/keuangan'
    | '/admin/reservasi'
    | '/admin/reward'
    | '/admin/tournament'
    | '/admin/voucher'
    | '/admin/coach/$coachId/hub'
    | '/admin/coach/$coachId/jadwal'
    | '/admin/tournament/$tournamentId/edit'
    | '/admin/tournament/$tournamentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/ai-assistant'
    | '/admin/coach'
    | '/admin/fnb'
    | '/admin/instruktur'
    | '/admin/keuangan'
    | '/admin/match'
    | '/admin/notifikasi'
    | '/admin/pengaturan'
    | '/admin/pengguna'
    | '/admin/program'
    | '/admin/reservasi'
    | '/admin/reward'
    | '/admin/tournament'
    | '/admin/voucher'
    | '/admin/'
    | '/admin/fnb/transaksi'
    | '/admin/keuangan/okupansi'
    | '/admin/keuangan/pendapatan'
    | '/admin/keuangan/reservasi'
    | '/admin/keuangan/transaksi'
    | '/admin/pengguna/$userId'
    | '/admin/reservasi/detail'
    | '/admin/reward/$rewardId'
    | '/admin/tournament/$tournamentId'
    | '/admin/tournament/new'
    | '/admin/voucher/$voucherId'
    | '/admin/coach/'
    | '/admin/fnb/'
    | '/admin/keuangan/'
    | '/admin/reservasi/'
    | '/admin/reward/'
    | '/admin/tournament/'
    | '/admin/voucher/'
    | '/admin/coach/$coachId/hub'
    | '/admin/coach/$coachId/jadwal'
    | '/admin/tournament/$tournamentId/edit'
    | '/admin/tournament/$tournamentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/voucher': {
      id: '/admin/voucher'
      path: '/voucher'
      fullPath: '/admin/voucher'
      preLoaderRoute: typeof AdminVoucherRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournament': {
      id: '/admin/tournament'
      path: '/tournament'
      fullPath: '/admin/tournament'
      preLoaderRoute: typeof AdminTournamentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reward': {
      id: '/admin/reward'
      path: '/reward'
      fullPath: '/admin/reward'
      preLoaderRoute: typeof AdminRewardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservasi': {
      id: '/admin/reservasi'
      path: '/reservasi'
      fullPath: '/admin/reservasi'
      preLoaderRoute: typeof AdminReservasiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/program': {
      id: '/admin/program'
      path: '/program'
      fullPath: '/admin/program'
      preLoaderRoute: typeof AdminProgramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengguna': {
      id: '/admin/pengguna'
      path: '/pengguna'
      fullPath: '/admin/pengguna'
      preLoaderRoute: typeof AdminPenggunaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifikasi': {
      id: '/admin/notifikasi'
      path: '/notifikasi'
      fullPath: '/admin/notifikasi'
      preLoaderRoute: typeof AdminNotifikasiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/match': {
      id: '/admin/match'
      path: '/match'
      fullPath: '/admin/match'
      preLoaderRoute: typeof AdminMatchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/keuangan': {
      id: '/admin/keuangan'
      path: '/keuangan'
      fullPath: '/admin/keuangan'
      preLoaderRoute: typeof AdminKeuanganRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instruktur': {
      id: '/admin/instruktur'
      path: '/instruktur'
      fullPath: '/admin/instruktur'
      preLoaderRoute: typeof AdminInstrukturRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fnb': {
      id: '/admin/fnb'
      path: '/fnb'
      fullPath: '/admin/fnb'
      preLoaderRoute: typeof AdminFnbRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coach': {
      id: '/admin/coach'
      path: '/coach'
      fullPath: '/admin/coach'
      preLoaderRoute: typeof AdminCoachRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-assistant': {
      id: '/admin/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/admin/ai-assistant'
      preLoaderRoute: typeof AdminAiAssistantRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/voucher/': {
      id: '/admin/voucher/'
      path: '/'
      fullPath: '/admin/voucher/'
      preLoaderRoute: typeof AdminVoucherIndexRouteImport
      parentRoute: typeof AdminVoucherRoute
    }
    '/admin/tournament/': {
      id: '/admin/tournament/'
      path: '/'
      fullPath: '/admin/tournament/'
      preLoaderRoute: typeof AdminTournamentIndexRouteImport
      parentRoute: typeof AdminTournamentRoute
    }
    '/admin/reward/': {
      id: '/admin/reward/'
      path: '/'
      fullPath: '/admin/reward/'
      preLoaderRoute: typeof AdminRewardIndexRouteImport
      parentRoute: typeof AdminRewardRoute
    }
    '/admin/reservasi/': {
      id: '/admin/reservasi/'
      path: '/'
      fullPath: '/admin/reservasi/'
      preLoaderRoute: typeof AdminReservasiIndexRouteImport
      parentRoute: typeof AdminReservasiRoute
    }
    '/admin/keuangan/': {
      id: '/admin/keuangan/'
      path: '/'
      fullPath: '/admin/keuangan/'
      preLoaderRoute: typeof AdminKeuanganIndexRouteImport
      parentRoute: typeof AdminKeuanganRoute
    }
    '/admin/fnb/': {
      id: '/admin/fnb/'
      path: '/'
      fullPath: '/admin/fnb/'
      preLoaderRoute: typeof AdminFnbIndexRouteImport
      parentRoute: typeof AdminFnbRoute
    }
    '/admin/coach/': {
      id: '/admin/coach/'
      path: '/'
      fullPath: '/admin/coach/'
      preLoaderRoute: typeof AdminCoachIndexRouteImport
      parentRoute: typeof AdminCoachRoute
    }
    '/admin/voucher/$voucherId': {
      id: '/admin/voucher/$voucherId'
      path: '/$voucherId'
      fullPath: '/admin/voucher/$voucherId'
      preLoaderRoute: typeof AdminVoucherVoucherIdRouteImport
      parentRoute: typeof AdminVoucherRoute
    }
    '/admin/tournament/new': {
      id: '/admin/tournament/new'
      path: '/new'
      fullPath: '/admin/tournament/new'
      preLoaderRoute: typeof AdminTournamentNewRouteImport
      parentRoute: typeof AdminTournamentRoute
    }
    '/admin/tournament/$tournamentId': {
      id: '/admin/tournament/$tournamentId'
      path: '/$tournamentId'
      fullPath: '/admin/tournament/$tournamentId'
      preLoaderRoute: typeof AdminTournamentTournamentIdRouteImport
      parentRoute: typeof AdminTournamentRoute
    }
    '/admin/reward/$rewardId': {
      id: '/admin/reward/$rewardId'
      path: '/$rewardId'
      fullPath: '/admin/reward/$rewardId'
      preLoaderRoute: typeof AdminRewardRewardIdRouteImport
      parentRoute: typeof AdminRewardRoute
    }
    '/admin/reservasi/detail': {
      id: '/admin/reservasi/detail'
      path: '/detail'
      fullPath: '/admin/reservasi/detail'
      preLoaderRoute: typeof AdminReservasiDetailRouteImport
      parentRoute: typeof AdminReservasiRoute
    }
    '/admin/pengguna/$userId': {
      id: '/admin/pengguna/$userId'
      path: '/$userId'
      fullPath: '/admin/pengguna/$userId'
      preLoaderRoute: typeof AdminPenggunaUserIdRouteImport
      parentRoute: typeof AdminPenggunaRoute
    }
    '/admin/keuangan/transaksi': {
      id: '/admin/keuangan/transaksi'
      path: '/transaksi'
      fullPath: '/admin/keuangan/transaksi'
      preLoaderRoute: typeof AdminKeuanganTransaksiRouteImport
      parentRoute: typeof AdminKeuanganRoute
    }
    '/admin/keuangan/reservasi': {
      id: '/admin/keuangan/reservasi'
      path: '/reservasi'
      fullPath: '/admin/keuangan/reservasi'
      preLoaderRoute: typeof AdminKeuanganReservasiRouteImport
      parentRoute: typeof AdminKeuanganRoute
    }
    '/admin/keuangan/pendapatan': {
      id: '/admin/keuangan/pendapatan'
      path: '/pendapatan'
      fullPath: '/admin/keuangan/pendapatan'
      preLoaderRoute: typeof AdminKeuanganPendapatanRouteImport
      parentRoute: typeof AdminKeuanganRoute
    }
    '/admin/keuangan/okupansi': {
      id: '/admin/keuangan/okupansi'
      path: '/okupansi'
      fullPath: '/admin/keuangan/okupansi'
      preLoaderRoute: typeof AdminKeuanganOkupansiRouteImport
      parentRoute: typeof AdminKeuanganRoute
    }
    '/admin/fnb/transaksi': {
      id: '/admin/fnb/transaksi'
      path: '/transaksi'
      fullPath: '/admin/fnb/transaksi'
      preLoaderRoute: typeof AdminFnbTransaksiRouteImport
      parentRoute: typeof AdminFnbRoute
    }
    '/admin/tournament/$tournamentId/': {
      id: '/admin/tournament/$tournamentId/'
      path: '/'
      fullPath: '/admin/tournament/$tournamentId/'
      preLoaderRoute: typeof AdminTournamentTournamentIdIndexRouteImport
      parentRoute: typeof AdminTournamentTournamentIdRoute
    }
    '/admin/tournament/$tournamentId/edit': {
      id: '/admin/tournament/$tournamentId/edit'
      path: '/edit'
      fullPath: '/admin/tournament/$tournamentId/edit'
      preLoaderRoute: typeof AdminTournamentTournamentIdEditRouteImport
      parentRoute: typeof AdminTournamentTournamentIdRoute
    }
    '/admin/coach/$coachId/jadwal': {
      id: '/admin/coach/$coachId/jadwal'
      path: '/$coachId/jadwal'
      fullPath: '/admin/coach/$coachId/jadwal'
      preLoaderRoute: typeof AdminCoachCoachIdJadwalRouteImport
      parentRoute: typeof AdminCoachRoute
    }
    '/admin/coach/$coachId/hub': {
      id: '/admin/coach/$coachId/hub'
      path: '/$coachId/hub'
      fullPath: '/admin/coach/$coachId/hub'
      preLoaderRoute: typeof AdminCoachCoachIdHubRouteImport
      parentRoute: typeof AdminCoachRoute
    }
  }
}

interface AdminCoachRouteChildren {
  AdminCoachIndexRoute: typeof AdminCoachIndexRoute
  AdminCoachCoachIdHubRoute: typeof AdminCoachCoachIdHubRoute
  AdminCoachCoachIdJadwalRoute: typeof AdminCoachCoachIdJadwalRoute
}

const AdminCoachRouteChildren: AdminCoachRouteChildren = {
  AdminCoachIndexRoute: AdminCoachIndexRoute,
  AdminCoachCoachIdHubRoute: AdminCoachCoachIdHubRoute,
  AdminCoachCoachIdJadwalRoute: AdminCoachCoachIdJadwalRoute,
}

const AdminCoachRouteWithChildren = AdminCoachRoute._addFileChildren(
  AdminCoachRouteChildren,
)

interface AdminFnbRouteChildren {
  AdminFnbTransaksiRoute: typeof AdminFnbTransaksiRoute
  AdminFnbIndexRoute: typeof AdminFnbIndexRoute
}

const AdminFnbRouteChildren: AdminFnbRouteChildren = {
  AdminFnbTransaksiRoute: AdminFnbTransaksiRoute,
  AdminFnbIndexRoute: AdminFnbIndexRoute,
}

const AdminFnbRouteWithChildren = AdminFnbRoute._addFileChildren(
  AdminFnbRouteChildren,
)

interface AdminKeuanganRouteChildren {
  AdminKeuanganOkupansiRoute: typeof AdminKeuanganOkupansiRoute
  AdminKeuanganPendapatanRoute: typeof AdminKeuanganPendapatanRoute
  AdminKeuanganReservasiRoute: typeof AdminKeuanganReservasiRoute
  AdminKeuanganTransaksiRoute: typeof AdminKeuanganTransaksiRoute
  AdminKeuanganIndexRoute: typeof AdminKeuanganIndexRoute
}

const AdminKeuanganRouteChildren: AdminKeuanganRouteChildren = {
  AdminKeuanganOkupansiRoute: AdminKeuanganOkupansiRoute,
  AdminKeuanganPendapatanRoute: AdminKeuanganPendapatanRoute,
  AdminKeuanganReservasiRoute: AdminKeuanganReservasiRoute,
  AdminKeuanganTransaksiRoute: AdminKeuanganTransaksiRoute,
  AdminKeuanganIndexRoute: AdminKeuanganIndexRoute,
}

const AdminKeuanganRouteWithChildren = AdminKeuanganRoute._addFileChildren(
  AdminKeuanganRouteChildren,
)

interface AdminPenggunaRouteChildren {
  AdminPenggunaUserIdRoute: typeof AdminPenggunaUserIdRoute
}

const AdminPenggunaRouteChildren: AdminPenggunaRouteChildren = {
  AdminPenggunaUserIdRoute: AdminPenggunaUserIdRoute,
}

const AdminPenggunaRouteWithChildren = AdminPenggunaRoute._addFileChildren(
  AdminPenggunaRouteChildren,
)

interface AdminReservasiRouteChildren {
  AdminReservasiDetailRoute: typeof AdminReservasiDetailRoute
  AdminReservasiIndexRoute: typeof AdminReservasiIndexRoute
}

const AdminReservasiRouteChildren: AdminReservasiRouteChildren = {
  AdminReservasiDetailRoute: AdminReservasiDetailRoute,
  AdminReservasiIndexRoute: AdminReservasiIndexRoute,
}

const AdminReservasiRouteWithChildren = AdminReservasiRoute._addFileChildren(
  AdminReservasiRouteChildren,
)

interface AdminRewardRouteChildren {
  AdminRewardRewardIdRoute: typeof AdminRewardRewardIdRoute
  AdminRewardIndexRoute: typeof AdminRewardIndexRoute
}

const AdminRewardRouteChildren: AdminRewardRouteChildren = {
  AdminRewardRewardIdRoute: AdminRewardRewardIdRoute,
  AdminRewardIndexRoute: AdminRewardIndexRoute,
}

const AdminRewardRouteWithChildren = AdminRewardRoute._addFileChildren(
  AdminRewardRouteChildren,
)

interface AdminTournamentTournamentIdRouteChildren {
  AdminTournamentTournamentIdEditRoute: typeof AdminTournamentTournamentIdEditRoute
  AdminTournamentTournamentIdIndexRoute: typeof AdminTournamentTournamentIdIndexRoute
}

const AdminTournamentTournamentIdRouteChildren: AdminTournamentTournamentIdRouteChildren =
  {
    AdminTournamentTournamentIdEditRoute: AdminTournamentTournamentIdEditRoute,
    AdminTournamentTournamentIdIndexRoute:
      AdminTournamentTournamentIdIndexRoute,
  }

const AdminTournamentTournamentIdRouteWithChildren =
  AdminTournamentTournamentIdRoute._addFileChildren(
    AdminTournamentTournamentIdRouteChildren,
  )

interface AdminTournamentRouteChildren {
  AdminTournamentTournamentIdRoute: typeof AdminTournamentTournamentIdRouteWithChildren
  AdminTournamentNewRoute: typeof AdminTournamentNewRoute
  AdminTournamentIndexRoute: typeof AdminTournamentIndexRoute
}

const AdminTournamentRouteChildren: AdminTournamentRouteChildren = {
  AdminTournamentTournamentIdRoute:
    AdminTournamentTournamentIdRouteWithChildren,
  AdminTournamentNewRoute: AdminTournamentNewRoute,
  AdminTournamentIndexRoute: AdminTournamentIndexRoute,
}

const AdminTournamentRouteWithChildren = AdminTournamentRoute._addFileChildren(
  AdminTournamentRouteChildren,
)

interface AdminVoucherRouteChildren {
  AdminVoucherVoucherIdRoute: typeof AdminVoucherVoucherIdRoute
  AdminVoucherIndexRoute: typeof AdminVoucherIndexRoute
}

const AdminVoucherRouteChildren: AdminVoucherRouteChildren = {
  AdminVoucherVoucherIdRoute: AdminVoucherVoucherIdRoute,
  AdminVoucherIndexRoute: AdminVoucherIndexRoute,
}

const AdminVoucherRouteWithChildren = AdminVoucherRoute._addFileChildren(
  AdminVoucherRouteChildren,
)

interface AdminRouteChildren {
  AdminAiAssistantRoute: typeof AdminAiAssistantRoute
  AdminCoachRoute: typeof AdminCoachRouteWithChildren
  AdminFnbRoute: typeof AdminFnbRouteWithChildren
  AdminInstrukturRoute: typeof AdminInstrukturRoute
  AdminKeuanganRoute: typeof AdminKeuanganRouteWithChildren
  AdminMatchRoute: typeof AdminMatchRoute
  AdminNotifikasiRoute: typeof AdminNotifikasiRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminPenggunaRoute: typeof AdminPenggunaRouteWithChildren
  AdminProgramRoute: typeof AdminProgramRoute
  AdminReservasiRoute: typeof AdminReservasiRouteWithChildren
  AdminRewardRoute: typeof AdminRewardRouteWithChildren
  AdminTournamentRoute: typeof AdminTournamentRouteWithChildren
  AdminVoucherRoute: typeof AdminVoucherRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiAssistantRoute: AdminAiAssistantRoute,
  AdminCoachRoute: AdminCoachRouteWithChildren,
  AdminFnbRoute: AdminFnbRouteWithChildren,
  AdminInstrukturRoute: AdminInstrukturRoute,
  AdminKeuanganRoute: AdminKeuanganRouteWithChildren,
  AdminMatchRoute: AdminMatchRoute,
  AdminNotifikasiRoute: AdminNotifikasiRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminPenggunaRoute: AdminPenggunaRouteWithChildren,
  AdminProgramRoute: AdminProgramRoute,
  AdminReservasiRoute: AdminReservasiRouteWithChildren,
  AdminRewardRoute: AdminRewardRouteWithChildren,
  AdminTournamentRoute: AdminTournamentRouteWithChildren,
  AdminVoucherRoute: AdminVoucherRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
